### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by HuskyCodez** [palahsu/MBomb#3]
i opened the file and it threw me this error:

_Traceback (most recent call last):
  File "C:\Users\jktem\Downloads\MBomb-master\MBomb-master\MBomb.py", line 8, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 37, in <module>
NameError: name 'raw_input' is not defined_

**Comment by palahsu** [comment]
> i opened the file and it threw me this error:
> 
> _Traceback (most recent call last): File "C:\Users\jktem\Downloads\MBomb-master\MBomb-master\MBomb.py", line 8, in eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'','exec')) File "", line 37, in NameError: name 'raw_input' is not defined_

Now it's updated! please, try again with **python2 MBomb.py** and **make sure you Turn On gmail lesssecure option** https://www.google.com/settings/security/lesssecureapps
