### ISSUE TITLE
cd Mbomb.py error

### ISSUE THREAD

**Issue by abarava** [palahsu/MBomb#4]
kali@kali:~#  cd MBomb.py
-bash: cd: MBomb.py: No such file or directory
i am sure i installed mbomb file by git clone https://github.com/palahsu/MBomb.git

**Comment by palahsu** [comment]
There are two files **MBomb Pro** and **MBomb**, which one you getting problem? And **please, clone this git another directory/folder** on your drive, make sure you **installed all requirements**. Thanks

**Comment by abarava** [comment]
root@:~# git clone https://github.com/palahsu/MBomb.git
Cloning into 'MBomb'...
remote: Enumerating objects: 100, done.
remote: Counting objects: 100% (100/100), done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 100 (delta 52), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (100/100), 420.54 KiB | 4.08 MiB/s, done.
Resolving deltas: 100% (52/52), done.
root@:~# cd MBomb.py
-bash: cd: MBomb.py: No such file or directory

this one

**Comment by palahsu** [comment]
Oops, why you write cd MBomb.py ! **it's only cd MBomb**

**Comment by palahsu** [comment]
`git clone https://github.com/palahsu/MBomb.git`

`cd MBomb`

`python MBomb.py` or `python2 MBomb.py`

**Comment by abarava** [comment]
because  this
How to use:
pkg install python2 -y

pkg install git -y

git clone https://github.com/palahsu/MBomb.git

cd MBomb.py

python MBomb.py or python2 MBomb.py

**Comment by palahsu** [comment]
it was my mistake...you can check previous issue i wrote https://github.com/palahsu/MBomb/issues/1

it;s only **cd MBomb**

**Comment by palahsu** [comment]
@abarava **TRY THIS!** https://github.com/palahsu/MBomb/issues/4#issuecomment-784872630

**Comment by abarava** [comment]
thank you but there are another error

root@:~# cd MBomb
root@:~/MBomb# python2 MBomb.py
Traceback (most recent call last):
  File "MBomb.py", line 8, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 13, in <module>
ImportError: No module named tqdm
root@:~/MBomb# python MBomb.py
Traceback (most recent call last):
  File "MBomb.py", line 8, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 13, in <module>
ImportError: No module named tqdm

**Comment by palahsu** [comment]
Please, **Try again, I uploaded updated version!**
