### ISSUE TITLE
MBomb Verson Updates!

### ISSUE THREAD

**Issue by palahsu** [palahsu/MBomb#5]
Use version 2!

https://github.com/palahsu/MBomb/tree/master/MBomb%20v2

**Comment by abarava** [comment]
still have same problem

root@:~/MBomb# python2 MBomb.py
Traceback (most recent call last):
  File "MBomb.py", line 8, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 13, in <module>
ImportError: No module named tqdm
root@:~/MBomb# python MBomb.py
Traceback (most recent call last):
  File "MBomb.py", line 8, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 13, in <module>
ImportError: No module named tqdm

**Comment by palahsu** [comment]
do you have telegram or messenger ?? contact me ( https://t.me/AD0000000 )
